### ISSUE TITLE
Add link to macOS Application built by GitHub Actions

### ISSUE THREAD

**Issue by averms** [mpv-player/mpv.io#111]
[Here is an example of the latest build][a] as of mpv-player/mpv@6179995dd7ef576073e184abd01fd34890e1b59f. I've been running one of these for a while now on my laptop and it seems to work fine.

cc: @Akemi

[a]: https://github.com/mpv-player/mpv/actions/runs/8526130178

**Comment by Akemi** [comment]
i am not sure this would be a good move. do we want to set a precedence of officially provided builds? though the bigger problem is, those builds are greatly restricted on what versions of macOS they work, eg the arm build only works on macOS 14 and so on. i am not really planning to make builds with a lower minimum target, since this would be a whole lot more work. there will be issues for sure that not all builds work on all supported macOS versions (>= 10.15) if we start linking those.

**Comment by kasper93** [comment]
> do we want to set a precedence of officially provided builds?

I think it would be still better than endorsing some random unvetted builds. We already link to "some" builds and it is worse that they are out of our control than, linking to our CI. But of course they are "third-party" so not our responsibility, but once they are linked on the main project page it kinda become our responsibility to moderate them.

That said, CI builds are mostly usable for testing core mpv only, they are missing some dependencies that may be useful in certain usecases, that's why at least in Windows case, shinchiro's builds are sort of the main mpv builds to use.

**Comment by Akemi** [comment]
that's basically what the builds from stolendata for macOS are.

i fear linking our mac CI builds as official builds will leads into a lot of work:
- (cross) compiling for intel and arm
- building for a minimum target 10.15
- building all dependencies from source with minimum target 10.15
  - this will lead to pretty big increase in build time
- providing full featured builds

or we link them as test builds with certain restrictions. though it seems we won't have any intel build anymore in 2-3 years.

**Comment by averms** [comment]
That's fair.

> providing full featured builds

What features are missing from the current build?

**Comment by Akemi** [comment]
> What features are missing from the current build?

i didn't look at it closely but some optional dependencies are missing, and i believe some feature aren't legally redistributable because of licensing(?)
