### ISSUE TITLE
Fedora , RHEL, CentOS packages from RPM Fusion

### ISSUE THREAD

**Issue by kwizart** [mpv-player/mpv.io#61]
Hi,

I would like to mention that mpv is packaged for Fedora , RHEL and CentOS on RPM Fusion.
RPM Fusion is a community based project with more than 50~ active contributors.

https://rpmfusion.org/Configuration
mpv 0.23 on EL7
mpv 0.27.x on current Fedora
mpv 0.28.x on development's version (f28/rawhide)

Package repository https://github.com/rpmfusion/mpv/tree/el7 (github mirror).

Thx

**Comment by Ricky-Tigg** [comment]
Hello (author, developers). A comparison involving the present software with another one, led me to visit the related site, in order to download this software, **as it and in its latest version**. Having noticed in the section covering the installation the non-presence of a mention related to RPM OSs, i could reasonably conclude that it was not supported by my Linux distribution. Lately i noticed it to be supported. Pity, as i had to waste time to figure out it. A mention in the site would have avoided it. That was though clearly suggested in the present report.
